apiVersion: v1
kind: Service
metadata:
  name: mm-user-api
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: mm-user-api
    tier: api
  type: ClusterIP
---