
name: CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: mm-user-api

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      #- name: Cache Maven packages
      #  #This action allows caching dependencies and build outputs to improve workflow execution time.
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/.m2
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2
      #Build the application using Maven
      #- name: Build with Maven
      #  run: mvn -B package -DskipTests --file pom.xml
      #- name: Build the Docker image
      #  run: docker build -t np123dev/user_manager .
       
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: np123dev/user_manager:1.0.${{ github.run_number }} , np123dev/user_manager:latest
      
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          
      - name: Deploy
        run: |-
          kubectl apply -k kubernetes/user_manager/overlays/gke
          kubectl set image deployment/$DEPLOYMENT_NAME mm-user-api=np123dev/user_manager:1.0.${{ github.run_number }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME
